### ISSUE TITLE
Difference between generated and result of link on the website

### ISSUE THREAD

**Issue by uy-rrodriguez** [itsthatguy/avatars-api-middleware#105]
Dear all,

I was trying out the library on your website https://api.adorable.io/ and the result of using the embedded tool is different when directly opneing the generated link. For e.g. the result for abott@adorable.io is a pink-ish face, whereas https://api.adorable.io/avatars/285/abott@adorable.png draws a completely different yellow-ish avatar.

Is it a problem on versions?

**Comment by rylnd** [comment]
Hey @uy-rrodriguez ! I believe the difference here is due to the value being different: your first example is using `abott@adorable.io`, while the second is using `abott@adorable` (I believe the `.png` is excluded, but it's been a while 😅).
